name: Build APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install PWABuilder CLI
        run: npm install -g @pwabuilder/cli
      - name: Build APK
        run: pwabuilder https://tvuj-web-url.com --android
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: APK
          path: ./android/app/build/outputs/**/*.apk
